baseURL = 'https://sarang-26.github.io/'
languageCode = 'en-us'
title = "Sarang's Logs"
theme = 'PaperMod'

[params]
env = "production"
description = ""
author = "Theme PaperMod"
defaultTheme = "auto"
ShowShareButtons = true
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = false 
tableOfContents = true

    [params.homeInfoParams]
    Title= "💡Bytes of Brains💡"
    Content='''I am documenting my learning notes in these blogs, besides I genuinely enjoy applying maths to solve real world problems. '''

    [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/sarang-sonar-93227a1b7/"
    
    [[params.socialIcons]]
    name = "github"
    url = "https://github.com/sarang-26"

[[menu.main]]
    name = "Posts"
    weight=10
    identifier = "posts"
    url="posts/"
[[menu.main]]
    name = "Archive"
    weight=20
    identifier = "archive"
    url="archives/"
[[menu.main]]
    name = "Search"
    weight=30
    identifier = "search"
    url="search/"
[[menu.main]]
    name = "Tags"
    weight=40
    identifier = "tags"
    url="tags/"
[[menu.main]]
    name = "FAQ"
    weight=30
    identifier = "faq"
    url="faq/"

[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'images'
target = 'static/images'

